@startuml test
skinparam style strictuml
skinparam sequenceMessageAlign center
title Gennemse Produktion

actor Actor as user

participant ":Controller" as CO


participant ":EmployeeRepository" as ER

user -> CO ++: GennemsetAfMedarbejder(initialer:string)
    CO -> ER ++: DoesExist(initialer:string)

    return
return




