@startuml test
skinparam style strictuml
skinparam sequenceMessageAlign center
title Gennemse Produktion


Actor Actor as user

participant ":Controller" as CO

participant ":ProductionRepository" as PR
participant ":ProductionTrayRepository" as PTR

user -> CO ++: vælgeProduktionsbakke(navn:string)
    

    CO -> PR ++: GetProductionTray(navn:string)
    
    PR -> PTR ++:  GetTray(name:String)
    return produktionsbakke:ProductionTray

    return produktionsbakke:ProductionTray
    
return produktionsbakke:ProductionTray




